language: node_js
before_script:
  - npm install -g grunt-cli
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a0466f893feff9f941f1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
